jbloomAus/SAELens

sae_training/train_sae_on_language_model.py

Setting `feature_sampling_method = None` causes `train_sae_on_language_model.py` to fail on line 67:
```python
if (feature_sampling_method.lower()=="anthropic") and ((n_training_steps + 1) % dead_feature_window == 0):
```
This is a quick fix.

Allow sampling method to be None

---

sae_training/config.py

This makes finding the correct run on WandB a _lot_ easier if you're varying one of the hyperparameters that aren't included in the default run name (e.g. I'm currently training SAEs on multiple hook points so I really need to see the hook name on the WandB dashboard to find the run I'm looking for).

Added run name to config

---

sae_training/cache_activations_runner.py
sae_training/utils.py

There was a bug where you could pass `buffer_idx_range=(0, 1)` into `shuffle_activations_pairwise`, it wouldn't raise an exception like it was supposed to and then get stuck in an infinite loop trying to find two non-identical indices within that range.
This was particularly likely to happen during the final shuffling when caching activations, so I've added an if statement there to make sure final pairwise shuffling doesn't happen if there's only 1 cache file.

Fixed edge case in activation cache shuffling

---

.github/workflows/tests.yml
.gitignore
README.md
makefile
pyproject.toml
requirements.txt
sae_analysis/dashboard_runner.py
sae_analysis/visualizer/data_fns.py
sae_analysis/visualizer/html_fns.py
sae_analysis/visualizer/model_fns.py
sae_training/activations_store.py
sae_training/cache_activations_runner.py
sae_training/config.py
sae_training/evals.py
sae_training/geom_median/src/geom_median/numpy/main.py
sae_training/geom_median/src/geom_median/numpy/utils.py
sae_training/geom_median/src/geom_median/numpy/weiszfeld_array.py
sae_training/geom_median/src/geom_median/numpy/weiszfeld_list_of_array.py
sae_training/geom_median/src/geom_median/torch/main.py
sae_training/geom_median/src/geom_median/torch/utils.py
sae_training/geom_median/src/geom_median/torch/weiszfeld_array.py
sae_training/geom_median/src/geom_median/torch/weiszfeld_list_of_array.py
sae_training/lm_runner.py
sae_training/optim.py
sae_training/toy_model_runner.py
sae_training/toy_models.py
sae_training/train_sae_on_language_model.py
sae_training/train_sae_on_toy_model.py
scripts/generate_dashboards.py

This PR sets up [Poetry](https://python-poetry.org/) for dependency management.
In the process of adding this, this PR does the following:
- removes `pylint` from `requirements.txt` and replaces it with `flake8`, since all the linting in CI uses flake8.
- adds `isort` since it's referenced in the `.vscode` config, but seemed to be absent from the actual requirements
- updates the Github Actions config to install via Poetry, and also check `black` and `isort` formatting
- updates the `Makefile` to use Poetry, and fills in the `make format` and `make check-format` commands
- runs `black` and `isort`, which resulted in a lot of reformatting
- Updates the `README` to reference Poetry
This PR leaves the following out:
- Leaves `requirements.txt` in case users are already relying on this to …

chore: using poetry for dependency management

---

.flake8
.github/workflows/tests.yml
sae_analysis/dashboard_runner.py
sae_analysis/visualizer/data_fns.py
sae_analysis/visualizer/html_fns.py
sae_analysis/visualizer/model_fns.py
sae_analysis/visualizer/utils_fns.py
sae_training/activations_store.py
sae_training/lm_runner.py
sae_training/sparse_autoencoder.py
sae_training/toy_model_runner.py
sae_training/toy_models.py
sae_training/train_sae_on_toy_model.py
scripts/generate_dashboards.py
tests/benchmark/test_toy_model_sae_runner.py
tests/unit/test_sparse_autoencoder.py

This PR enables the full set of flake8 default rules by using `extend-select` and `extend-ignore` instead of `select` and `ignore`.
In addition, this PR makes the following notable changes:
- Simplifies the Github action to just run `flake8 .` so it will use the same settings as the flake8 on local
- Ignores the `geom_median` dir, since that's its own project, and its unclear if that should be linted by this
- ignores `E402` in `dashboard_runner.py` and `generate_dashboards.py` due to those files having `sys.path.append()` calls above imports. It's not clear to me why those calls are there, so I just left a TODO and ignored the error
- removes `# noqa` statements that didn't seem necessary
- adds `r` to regex strings, which I think was probably the intention anyway
closes #14

chore: enable full flake8 default rules list

---

.pre-commit-config.yaml
makefile
sae_training/geometric_median.py
sae_training/train_sae_on_language_model.py

The 'torch' version of the geometric median code uses lists and numpy arrays a bunch, here's a true torch version
Test it by running sae_training/geometric_median.py
It's about a 5x speedup on cpu and 1000x speedup on gpu :D 
(please double check my changes to train_sae_on_language_model.py, I'm running stuff on my own code base and haven't actually set up this environment to try the training! Also consider increasing max iter since it's faster.)

Faster geometric median.

---

sae_analysis/dashboard_runner.py

Issue:
DashboardRunner fails when use_wandb=False
Cause:
DashboardRunner does an assert at the end to check if "run" (a wandb variable) is not None, even if use_wandb is set to False. This will always fail when use_wandb is False because "run" isn't initialized.
Fix:
Add check for use_wandb before doing this assert and other code for uploading to wandb.
Possible modifications / other considerations:
Should we still zip up the folder and/or delete it?

FIX: Don't check wandb assert if not using wandb

---

.github/workflows/deploy_docs.yml
docs/about/contributing.md
makefile

This PR adds a contribution guide page to the docs, outlining how to get set up for development and what to run to make sure your code is up to par before opening a PR. This PR also adds some more makefile helpers to facilitate easier checking of code by contributors.
Some things to note:
- I didn't include anything about autodocs or docstring comments in the guide, since I don't think mkdocs supports autodoc. If we have a preferred docstring style we should consider adding a linting rule for it.
- I didn't add a demo `.vscode/settings.json` config, in case we change to use `ruff` for litning/formatting, as that would require a different vscode setup. If we want to stick with what we have, I'll add that to the docs too.
The rendered docs page is shown below

adding a contribution guide to docs

---

sae_training/optim.py
tests/unit/test_optim.py

This PR adds tests to the `get_scheduler()` function, and improves type hinting by listing all optional arguments instead of relying on `kwargs` so editors can auto-complete the available options.
In the process of writing these tests, I found we have an inconsistency with our `cosineannealingwarmup` which we implement manually, and  `cosineannealing`, which is implemented by pytorch. Specifically, what we're calling `lr_end` is not the same as `eta_min` if `lr_end != 0.0`. We need to either multiply `lr_end` by `lr` when passing to `eta_min` in `cosineannealing`, or divide `lr_end` by `lr` when using our `cosineannealingwarmup` function. This is likely not a big deal since I don't think we use `cosineannealingwarmup` by default, but we should be careful with this when using cosine …

Adding tests to get_scheduler

---

.github/workflows/deploy_docs.yml

I'm not 100% sure this is the issue with the docs deploy, but I think the problem is that the `gh-pages` branch isn't stricly upsteam of the attempts to push to `gh-pages`, thus causes the deploy to get rejected. Hopefully adding `--force` to the CI step should fix the issue.

attempting to fix docs deploy

---

pyproject.toml
requirements.txt

CI is [currently broken](https://github.com/jbloomAus/mats_sae_training/actions/runs/8509749352/job/23305929241?pr=62) because the `eindex` dependency just changed its name to `eindex-callum` (see [commit](https://github.com/callummcdougall/eindex/commit/695dbb9e9a2a3224c28485fb6e0b8b92c274dcbd)), so our dependencies are now incorrect and we can't install our project. It looks like this dependency is never used in our project anyway, so this PR just removes it as a dependency entirely.

removing unused eindex depencency

---

sae_training/config.py
sae_training/optim.py
sae_training/train_sae_on_language_model.py
tests/unit/test_optim.py
tests/unit/test_train_sae_on_language_model.py

This PR adds a `lr_decay_steps` config option which will linearly decay learning rate to 0 at the end of training. This PR simplifies the `get_scheduler` function by removing `constantwithwarmup`, `linearwarmupdecay`, and `cosineannealingwarmup` options. Instead, any scheduler can now have a linear warmup and linear decay by setting the `lr_warm_up_steps` and `lr_decay_steps`.
This also required changing some of the options passed to `get_scheduler`. This function now takes in `lr` as well, since there's a discrepancy with how torch's cosine annealing scheduler works compared to how the other schedulers. Specifically, it seems that torch's cosine annealing actually sets the final LR to the value specified by eta_min, but the other schedulers don't know what the current learning rate is …

adding lr_decay_steps and refactoring get_scheduler

---

sae_training/config.py
sae_training/optim.py
sae_training/train_sae_on_language_model.py
tests/unit/test_optim.py
tests/unit/test_train_sae_on_language_model.py

This PR is a followup from #61. I realized after merging that I forgot to pass the `lr_decay_steps` option from the config through to the actual `get_scheduler()` function 🤦‍♂️. This PR fixes that, and also removes all the default values from the `get_scheduler()` function so the type checker will error if we forget to pass through a value from the config for any param to `get_scheduler()` moving forward.

passing accidentally overlooked scheduler opts

---

sae_training/activations_store.py
sae_training/cache_activations_runner.py
sae_training/config.py
sae_training/evals.py
sae_training/sae_group.py
sae_training/sparse_autoencoder.py
sae_training/train_sae_on_language_model.py
sae_training/utils.py
tests/unit/helpers.py
tests/unit/test_activations_store.py
tests/unit/test_sae_group.py
tests/unit/test_sparse_autoencoder.py
tests/unit/test_train_sae_on_language_model.py

This PR adds optional list typing for config params that can take a list of values for SAEGroup construction, and enables proper config typing for `ActivationsStore` and `SAEGroup` classes.
In #44, I originally tried to remove the config from `SAEGroup` entirely to avoid having the same config class passed to both SAE and SAEGroup, since SAE can't have any list values, but SAEGroup can. I think I was overthinking this, and just explicitly setting the SAEGroup fields that can be lists as optional lists, and adding some assertions in SAE construction that these cfg values are not lists seems to solve the problem. I also set some of these types on the SAE class itself so we can read the values from the SAE object instead of from `sae.cfg` to avoid needing to keep asserting that things aren't …

fixing config typing

---

.github/workflows/build.yml

This PR removes the `paths-ignore` key from the build workflow, as this may unintentionally block releases from running. Semantic-release will fail if when it comes time to publish a relase, the published commit is no longer the head commit in the repo. This is to avoid situations where an earlier commit might get a later version number than later commit if they both are merged at roughly the same time.
However, if the most recent commit is just a change to the README.md for example,  the `paths-ignore` can cause semantic-release to fail. If, due to the README.md change, it is no longer the most recent commit to the repo, semantic release will bail out assuming that the most recent CI run will pull in the changes and publish,  but due to the `paths-ignore`, CI never gets run and thus the …

fix: removing paths-ignore from action to avoid blocking releases

---

README.md
docs/index.md

This PR updates the README with the `pip install sae-lens` installation instructions (It looks like I overlooked this in #66), adds a PyPI version badge, and updates the badge URLs to point to the new SAELens repo isntead of the old repo name.

chore: updating README.md with pip install instructions and PyPI badge

---

tutorials/evaluating_your_sae.ipynb

While running through the tutorial notebook I encountered a couple of runtime errors - these are the smallest set of updates that get you something runnable, and generate html that looks like:
I'm sure given the dev speed this'll be out of date again soon, but this hopefully this suffices in the interim.

bugfix - minimum viable updates to tutorial notebook

---

.github/workflows/build.yml
sae_lens/training/config.py

This PR adds python 3.12 checks for CI, since it turns out that flake8 on 3.12 runs checks inside of f-strings, but on 3.11 and 3.10 it doesn't

chore: enabling python 3.12 checks for CI

---

sae_lens/toolkit/pretrained_saes.py
sae_lens/training/sparse_autoencoder.py
tests/unit/toolkit/test_pretrained_saes.py

Title basically says it all:
- Adds `convert_old_to_modern_saelens_format` to toolkit/pretrained_saes.py
- Adds test of above function
- Fixes a bug for non-mps loads in legacy loader

Adds function that converts old .pt pretrained SAEs to new folder format

---

.pre-commit-config.yaml
pyproject.toml

This PR pins all version of the pre-commit checks with the same version as used by CI, and removes extra flake8 checks

chore: setting up precommit to be consistent with CI

---

sae_lens/training/sparse_autoencoder.py
tests/unit/toolkit/test_pretrained_saes.py
tests/unit/training/test_sparse_autoencoder.py

Your library is too strict, which creates errors if loading state dicts that don't eg contain a scaling factor. I added a quick fix that won't raise errors when loading a state dict that only contains some parameters. This runs the risk that someone may accidentally load a state dict with too few parameters, which is bad? But seems pretty unlikely to me

Make load_state_dict use strict=False

---

sae_lens/analysis/neuronpedia_runner.py
tutorials/neuronpedia/neuronpedia.py

- Save a neuronpedia run's settings to a json file, so that when resuming a run later, you don't fat-finger a setting
- Skip batch json file if it already exists
- Save the sparsity setting to skipped_indexes.json

Improvements to Neuronpedia Runner

---

sae_lens/analysis/neuronpedia_integration.py
tests/unit/analysis/test_neuronpedia_integration.py

This adds a `make_neuronpedia_list_with_features` method that creates a list on neuronpedia with specified features via new neuronpedia API call.

feat: make a neuronpedia list with features via api call

---

tutorials/neuronpedia/neuronpedia.py

Allows resuming upload job to neuronpedia

Neuronpedia: allow resuming upload

---

docs/training_saes.md

Update default lr scheduler name in docs
Fixes #105 

chore: fix outdated lr_scheduler_name in docs

---

.vscode/settings.json
pyproject.toml
sae_lens/analysis/neuronpedia_integration.py
tests/unit/analysis/test_neuronpedia_integration.py
tutorials/neuronpedia/neuronpedia.py

This adds the ability to pull a neuronpedia feature, do autointerp and scoring on it locally (with openai key that's stored locally), then uploads it to neuronpedia.

API for generating autointerp + scoring for neuronpedia

---

sae_lens/training/sparse_autoencoder.py
tests/unit/training/test_sparse_autoencoder.py

This PR breaks up the forward() pass of the sparse autoencoder into separate encode() and decode() functions, so that users can e.g., just run the encoder or just run the decoder on input or SAE activations.
I'm not 100% sure I have the 'right' unit tests for these functions, so happy to iterate on those.
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
- [ x ] I have run `make check-ci` to check format and …

breaks up SAE.forward() into encode() and decode()

---

sae_lens/training/sparse_autoencoder.py
tests/unit/training/test_sparse_autoencoder.py

For L1 this does not effect anything as essentially it's calculating the abs() and average everything. For L2 this is problematic as L2 involves sum and sqrt. Unexpected behaviors occur when x is of shape (batch, sen_length, hidden_dim).

Fix: sparsity norm calculated at incorrect dimension.

---

sae_lens/training/config.py
sae_lens/training/lm_runner.py
sae_lens/training/train_sae_on_language_model.py

Adds torch autocasting to the SAE train step, improving throughput.
W&B dashboard showing no performance regression when autocasting to bf16 and moderate speedup/perf-per-time improvement: https://wandb.ai/tmcgrath/autocast%20testing/workspace
More performance could probably be obtained by compiling and autocasting the LLM and maybe by compiling the SAE. Other hyperparameters are also probably better for performance.

Add bf16 autocast

---

sae_lens/training/activations_store.py
sae_lens/training/config.py
sae_lens/training/evals.py
sae_lens/training/lm_runner.py
sae_lens/training/train_sae_on_language_model.py

Surfaces extra options for eval step: number of eval batches and number of sequences per eval batch. Adds an optional parameter to activations_store.get_batch_tokens to make this clean: now get_batch_tokens can get a number of sequences that differs from the value defined at init.
- [] I have added tests that prove my fix is effective or that my feature works
I've checked these locally but not added tests.

Change eval batch size

---

sae_lens/training/activations_store.py
sae_lens/training/config.py
sae_lens/training/evals.py
sae_lens/training/lm_runner.py
sae_lens/training/train_sae_on_language_model.py

This change accelerates training by enabling torch.compile (and providing compilation options) for LM and SAE as config flags. This substantially increases throughput over uncompiled models. 
W&B dashboard for performance comparison: https://wandb.ai/tmcgrath/compilation-checking/workspace

Add torch compile

---

docs/index.md

tiny - just missing a closing "

fix typo in training docs

---

sae_lens/training/cache_activations_runner.py
sae_lens/training/config.py
sae_lens/training/load_model.py
sae_lens/training/sae_group.py
sae_lens/training/session_loader.py
tests/unit/training/test_load_model.py
tests/unit/training/test_session_loader.py

Adds the `model_from_pretrained_kwargs` config parameter and associated code in order to allow full control over the `HookedTransformer` or `HookedMamba` model used to extract activations from. In my specific case this is required in order to load non-default checkpoints for Pythia models.
Doesn't affect performance for existing code

feat: Add model_from_pretrained_kwargs as config parameter

---

tests/unit/conftest.py

Pretty simple test change to add a pytest fixture that is run for every test, and use it to seed the RNG.
I don't strongly have evidence that not doing this caused test failures, or that doing it fixes them, but the principled case for doing this is pretty strong IMO and I can't think of any real downsides.
I think it's quite likely that there are other sources of non-determinism not fixed here (e.g. any non-global RNGs that are used in code), but incremental progress helps.
- none necessary
- This is *possible* (e.g. by testing the output of `torch.get_rng_state`) but it's hard to imagine a version of this test that catches actual bugs.
If you have implemented a training change, please indicate precisely how performance changes with respect to …

tools to make tests more deterministic

---

tests/unit/conftest.py

It looks like setting `torch.use_deterministic_algorithms(True)` in tests causes errors on CUDA >= 10.2. This setting isn't actually necessary for our tests, so this PR removes that option from the reproducability fixture.
Fixes #136

chore: remove use_deterministic_algorithms=True since it causes cuda errors

---

sae_lens/training/config.py
sae_lens/training/toy_model_runner.py
sae_lens/training/toy_models.py
tests/benchmark/test_toy_model_sae_runner.py
tests/unit/training/test_toy_models.py

Re-implements toy models as child classes of HookedRootModule. Most toy model functionality now lives in an abstract class, which specific toy models inherit from. Also adds some basic unit tests to toy models. Two toy models currently live in the toy model file:
- Anthropic's ReLU output model
- A model which trains using cross-entropy loss on a classification task with the same architecture as the ReLU output model
Fixes #85  (though there's still more toy model work to be done integrating with runners)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ I'm not sure how to do this ] I have made corresponding changes to the documentation
- [ I think …

Hooked toy model

---

sae_lens/training/evals.py

Currently evals.py includes a call to `torch.cuda.empty_cache()`. This causes inconsistent memory usage across runs, which makes OOMs unpredictable and might cause extra recompilation (though I'm not sure on this). `torch.cuda.empty_cache` doesn't actually free up additional memory for pytorch - it simply releases it from the pytorch allocator (I was surprised by this, discussion [here](https://pytorch.org/docs/stable/notes/cuda.html#memory-management) and [here](https://discuss.pytorch.org/t/about-torch-cuda-empty-cache/34232)). It's also not recommended for use by end-users except in edge cases, so I propose we remove it.
I've tested this change with and without compilation on GPT-2-S SAEs. All unit tests continue to pass.
- [] I have added …

Remove cuda cache emptying in evals.py

---

scripts/sweep-gpt2.py

Adds base sweep settings for gpt-2-small. Sweeps are intentionally relatively short: most of the action that tells us whether a sweep will be obviously bad seems to happen relatively quickly. Based on Anthropic SAE replication.
[W&B dashboard for this run](https://wandb.ai/tmcgrath/gpt-2-sweep-12may24/workspace).

Gpt 2 sweep

---

sae_lens/toolkit/pretrained_saes.py

Fixes a hardcoded device when loading pretrained attention-out SAEs

fix: hardcoded mps device in ckrk attn saes

---

scripts/ansible/README.md
scripts/ansible/configs_example/shared.yml
scripts/ansible/run-configs.yml

We'll probably delete the `automation` branch at some point, so the Ansible example config should point to a version that has the correct Ansible scripts (could also do `main` but would rather do a known working one)

Pin Ansible config example to a specific version, update docs

---

sae_lens/training/activations_store.py
sae_lens/training/evals.py
sae_lens/training/train_sae_on_language_model.py
scripts/sweep-gpt2-blocks.py
scripts/sweep-gpt2.py

Anthropic's SAE training code normalises activations before they enter the SAE so that their average L2 norm is sqrt(d_model). Although we have normalisation activation in the code, it is not currently applied during evals which both harms the cross-entropy loss and makes hyperparameter transfer across layers impossible as different layers have substantially different mean norms.
This PR changes estimation of the scale factor to occur once, with a larger sample size, before SAE training, and modifies the eval code to up- and downscale activations as part of the hook function as well as correctly estimate the L2 norm of activations that the SAE will actually see during training.
The code in this PR isn't the prettiest and I aim to create a tidier version next week but we need this …

Fix normalisation

---

sae_lens/__init__.py
sae_lens/training/batching.py
sae_lens/training/config.py
sae_lens/training/pretokenize_runner.py
tests/unit/training/test_batching.py
tests/unit/training/test_pretokenize_runner.py
tutorials/pretokenizing_datasets.ipynb

This PR adds a pretokenize runner which can be used to pre-tokenize / chunk / shuffle datasets and upload them to Huggingface. I plan on adding a follow-up PR in the future to harmonize the `ActivationsStore` to use the same logic for generating batches as is used here, but decided to hold off on that for now to avoid merge conflicts and to keep this PR more easily reviewable.
This PR has several design considerations after discussion in the OSMI slack:
- Support specifying a special token to use only at the beginning of every batch
- Support specifying a special token to use at the begging of each new sequence
- Support specifying a special token to use as a separator between sequences
- It should be possible for these tokens to occur one after another if desired (e.g. `seq 1 <eos> <bos> …

Pretokenize runner

---

CHANGELOG.md
pyproject.toml
sae_lens/__init__.py
sae_lens/training/config.py
sae_lens/training/optim.py
tests/unit/training/test_train_sae_on_language_model.py

Compiled SAEs currently break checkpointing. The root cause of this is that compiled models cannot be saved with torch.save(compiled_model), but should instead be saved using their state dict (see [PyTorch ref](https://pytorch.org/get-started/pytorch-2.0/#serialization)). 
The model checkpointing code serializes the compiled model using its state_dict, but `SAETrainContext.save` does not. The issue comes from `L1Scheduler` having a reference to the SAE, which has been compiled. When `SAETrainContext.save` is called, because `L1Scheduler` has no state_dict, the code attempts to save a compiled model, leading to a crash.
This PR adds a state dict to L1Scheduler, as well as restoring the L1Scheduler from that state dict, which now allows for proper serialisation.
Please delete options that …

Fix checkpointing of training state that includes a compiled SAE

---

sae_lens/pretrained_saes.yaml

- New SAEs in from pretrained. 
See HF repo here: https://huggingface.co/jbloom/Gemma-2b-Residual-Stream-SAEs
Load using from pretrained method here.
```python
import torch
from transformer_lens import HookedTransformer
from sae_lens import SparseAutoencoder, ActivationsStore
torch.set_grad_enabled(False)
model = HookedTransformer.from_pretrained("gemma-2b")
sparse_autoencoder = SparseAutoencoder.from_pretrained(
"gemma-2b-res-jb", # to see the list of available releases, go to: https://github.com/jbloomAus/SAELens/blob/main/sae_lens/pretrained_saes.yaml
"blocks.0.hook_resid_post" # change this to another specific SAE ID in the release if desired. 
)
activation_store = ActivationsStore.from_config(model, sparse_autoencoder.cfg)
```

add gemma-2b bootleg saes

---

scripts/wandb_to_hf.ipynb

We output trained models as Weights & Biases artifacts, but other users want to use HuggingFace model repos to get our trained SAEs. Currently this process is manual and somewhat time-consuming. This PR adds a notebook to automate transfer of models between W&B projects and HuggingFace repos.
Models in [this HF repo](https://huggingface.co/tommmcgrath/gpt2-small-mlp-out-saes/tree/main) were transferred using the notebook contained in this PR.

Add notebook to transfer W&B models to HF

---

sae_lens/training/activations_store.py
sae_lens/training/config.py
scripts/test-autocast-lm.py

Torch autocasting can provide a substantial speedup and reduce VRAM consumption for relatively little code complexity. We currently have the option to autocast the SAE but not the LM. Creating activations for SAE training takes up a lot of the training time so adding autocasting to LM activation fetching is a quick win.
This PR enables autocasting of LM activation fetching using a new config option: `autocast_lm`, which is set to False by default buut will caused the LM to be autocast when set to True. This only autocasts activation fetching; evals are left unaffected.
- [] Feature Dashboard Interpretability
This …

Enable autocast for LM activation creation

---

sae_lens/sae.py
tests/unit/training/test_sae_basic.py

Implements a simple SAE method for folding W_dec norm weights of Anthropic style SAEs into encoder such that W_dec features are unit norm. See Anthropic update here: https://transformer-circuits.pub/2024/april-update/index.html#training-saes
I have tested that the feature activations and sae out are as expected. It's possible we should make this the default when loading from pretrained (so that feature activations are conceptually what you expect them to be). I may submit a PR soon which makes this the case. 

feat: add w_dec_norm folding

---

sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
tests/benchmark/test_eval_all_loadable_saes.py
tests/unit/training/test_sae_training_runner.py

We temporarily had a situation where `SAE.load_from_pretrained` wasn't using the defaulting system we've got for `from_pretrained` (saes on HuggingFace). This refactor just moves the defaults (temporary hack) to a common function).
Fixes #168 

fix: share config defaulting between hf and local loading

---

sae_lens/sae.py
sae_lens/training/activations_store.py
sae_lens/training/sae_trainer.py
tests/benchmark/test_eval_all_loadable_saes.py
tests/unit/training/test_activations_store.py
tests/unit/training/test_sae_basic.py

Sometimes SAEs are trained on normalized activations. We should really be saving these with the norm scaling factor already folded in, but in the meantime I've written a convenience function to fold the scaling factor in and refactored it's calculation so the method belongs to the activation store. 
I think we're working up to a "processing step" in load from pretrained where we basically have this and similar stuff handled by default. 
- [] I have made corresponding changes to the documentation

feat: activation norm scaling factor folding

---

tutorials/Hooked_SAE_Transformer_Demo.ipynb

The current HookedSAETransformer demo is broken in [colab](https://colab.research.google.com/github/jbloomAus/SAELens/blob/main/tutorials/Hooked_SAE_Transformer_Demo.ipynb)
It was pip installing from the old TransformerLens branch rather than SAELens. This PR fixes that, and also updates some of the language in the demo to match SAELens (eg HookedSAE -> SAE).
- [x ] Bug fix (non-breaking change which fixes an issue)

Fix pip install in HookedSAETransformer Demo

---

README.md
docs/training_saes.md
pyproject.toml
sae_lens/__init__.py
sae_lens/pretokenize_runner.py
sae_lens/sae.py
sae_lens/sae_training_runner.py
sae_lens/training/sae_trainer.py
sae_lens/training/training_sae.py
tutorials/pretokenizing_datasets.ipynb

This PR fills out more of the training docs, including basic docs on the following topics:
- basic training setup
- logging to WandB
- checkpoints
- optimizers / schedulers
- dataset streaming / context size
- pretokenizing datasets
- activation caching
As part of this, this PR also standardizes and documents the pretokenization runner with as a class called `PretokenizeRunner`, and deprecated the previous `pretokenize_runner()` function. This commit is thus labeled a `feat` due to this new class.
A screenshot of the SAE training docs page is shown below:

feat:  updating training docs and standardizing pretokenize runner arch

---

sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_saes_directory.py
tests/benchmark/test_eval_all_loadable_saes.py
tests/unit/toolkit/test_pretrained_saes_directory.py

From pretrained.yaml now stores the expected L0 / variance explained on a test example in tests/benchmark. This is a first step towards having pre-trained model loading in CI. We'll likely need a GPU runner that can cache downloaded SAEs to do this properly.

add expected perf for pretrained

---

sae_lens/config.py
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/training/activations_store.py
sae_lens/training/training_sae.py
tests/benchmark/test_language_model_sae_runner.py
tests/unit/analysis/test_hooked_sae.py
tests/unit/analysis/test_hooked_sae_transformer.py
tests/unit/helpers.py
tests/unit/training/test_config.py

The newest version of Huggingface transformers won't allow loading old datasets that require allowing code execution without explicitly setting `trust_remote_code=True`. As a result, tests are now failing on CI since it loads the most recent version of transformers. This PR adds an option `dataset_trust_remote_code` which the user can set to allow this remote code execution so old datasets can be loaded in new versions of transformers, and also fixes CI.

fix: allow settings trust_remote_code for new huggingface version

---

tests/unit/training/test_activations_store.py

I ran unit tests locally with
`make check-ci`
Nearly all passed, but two failed 
```
==================================================================================== short test summary info =====================================================================================
FAILED tests/unit/training/test_activations_store.py::test_activations_store__shapes_look_correct_with_real_models_and_datasets[gpt2-tokenized] - datasets.exceptions.DatasetNotFoundError: Dataset 'apollo-research/sae-monology-pile-uncopyrighted-tokenizer-gpt2' doesn't exist on the Hub or cannot be accessed.
FAILED tests/unit/training/test_activations_store.py::test_activations_store_estimate_norm_scaling_factor[gpt2-tokenized] - datasets.exceptions.DatasetNotFoundError: Dataset …
```

Fix dataset naming issue (typo?) in unit test

---

tutorials/training_a_sparse_autoencoder.ipynb

When running the original `tutorials/training_a_sparse_autoencoder.ipynb` code I get an error informing me that there is a mismatch between the input length (512) and the given context length (256). 
```
ValueError: pretokenized dataset has context_size 512, but the provided context_size is 256.
```
The given dataset `apollo-research/roneneldan-TinyStories-tokenizer-gpt2` does in fact have 512 input ids per sample. Presumably the error was added after the tutorial was last updated. The check seems eminently reasonable to me so I don't think we should remove the check.
I have confirmed that `tiny-stories-1L-21M` has a context length of 2048 so this change is sensical, and I can confirm that the changed code works (I'm running it right now in fact)
```
Run name: …
```

prevent context size mismatch error in training turorial

---

pyproject.toml

We use the `@deprecated` operator, but for old versions of Python (3.10), we need to use the `typing-extensions` package to provide support. It looks like support for `@deprecated` was [added in v4.5.0](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-450-february-14-2023), but we don't actually pin the dependency in pyproject.toml, so it's possible for users to install an outdated version of the dependency and get an error when loading SAELens.
This fixes the issue by pinning the `typing-extensions` dependency to `>=v4.10.0`, which should be recent enough to have everything we depend on.
Fixes #203 

fix: pin typing-extensions version

---

sae_lens/config.py
sae_lens/sae_training_runner.py
sae_lens/training/activations_store.py
tests/benchmark/test_activations_store.py
tests/unit/training/test_activations_store.py
tests/unit/training/test_config.py
tests/unit/training/test_evals.py
tests/unit/training/test_sae_trainer.py
tests/unit/training/test_sae_training.py
tests/unit/training/test_sae_training_runner.py

Allows users to pass in datasets which are not on huggingface when training using the `SAETrainingRunner`
Code of the following kind (which is quite useful imo, especially when testing) now runs:
```python
... 
dataset: IterableDataset = cast(IterableDataset, load_dataset(
"apollo-research/roneneldan-TinyStories-tokenizer-gpt2",
split="train",
streaming=True,
trust_remote_code=True,
))
dataset = dataset.take(100)
sparse_autoencoder = SAETrainingRunner(cfg, dataset).run()
```
The changes are based on an existing pattern for passing in non-path datasets to the `ActivationStore`
Also added a more explicit error for when the activation buffer size is too large for the dataset passed in.
IMO we should give users the option of passing in `None` to the `dataset_path` across all kinds of config …

SAETrainingRunner takes optional HFDataset

---

sae_lens/evals.py
sae_lens/pretrained_saes.yaml
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/toolkit/pretrained_saes_directory.py
sae_lens/training/toy_models.py
tests/unit/toolkit/test_pretrained_saes_directory.py
tests/unit/training/test_sae_basic.py

We had a bug where we weren't scaling the decoder weights when using SAEs that had an activation norm factor scaling factor `normalize_activations = "expected_average_only_in"` which affected the quality of GPT2-Small MLP-Out SAEs (TM ones, not OAI) and the gemma-2b (base) layer 12 resid post SAE. 
Also, in order to have benchmark tests (not yet in CI) not fail due to warnings over dataset size matches, we've switched some SAE configs to tokenizing in real time (which slows them down unfortunately) - but this is solve-able if we make some pre-tokenized datasets with the right lengths. 

fix: Activation store factor unscaling fold fix

---

sae_lens/sae_training_runner.py

You can now pass a custom model override in as well as a dataset override when instantiating a `SAETrainingRunner`.
Code of the following kind now works:
```python
import os
from typing import cast
import torch
from datasets import IterableDataset, load_dataset
from sae_lens import LanguageModelSAERunnerConfig, SAETrainingRunner
if torch.cuda.is_available():
device = "cuda"
elif torch.backends.mps.is_available():
device = "mps"
else:
device = "cpu"
print("Using device:", device)
os.environ["TOKENIZERS_PARALLELISM"] = "false"
from transformer_lens import HookedTransformer
model = HookedTransformer.from_pretrained(
"tiny-stories-1L-21M"
)  # This will wrap huggingface models and has lots of nice utilities.
total_training_steps = 300  # probably we should do more
batch_size = 16 …
```

allow models to be passed in as overrides

---

docs/generate_sae_table.py
docs/sae_table.md
mkdocs.yml
pyproject.toml
sae_lens/pretrained_saes.yaml
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/training/toy_models.py
sae_lens/training/training_sae.py
tests/benchmark/test_eval_all_loadable_saes.py

I made a docs page which will load SAE Configs for all SAEs which can be loaded with `from_pretrained`. Had to do some refactoring which was a bit annoying but probably healthy. 

feat: make pretrained sae directory docs page

---

sae_lens/sae.py
sae_lens/training/sae_trainer.py
sae_lens/training/training_sae.py

- Convert to `sae.cfg.dtype` for consistency of dtype (not to float) to avoid errors associated with that.
- Convert to `float` when logging during evals to avoid `bfloat16` errors on cpu. 
Fixes (not raised yet)

fix: avoid bfloat16 errors in training gated saes

---

sae_lens/sae.py
sae_lens/training/training_sae.py

The gated SAE PR added a new encode method called `encode_gated` which is used by the sae training loop instead of `encode` when training SAEs. However this meant we had this new method called `encode_fn` which needs to be called to get the correct encode. Since this causes issues downstream if people don't know about this, I've renamed `encode_fn` to `encode` (so anyone calling encode gets the correct encode method) and `encode` to `encode_standard` so the code is more explicit about which encode is being used inside the package.

fix: rename encode_fn to encode and encode to encode_standard

---

sae_lens/evals.py

As mentioned in #163 , zero-ablation hooks for single-head SAEs had a bug. I resolve that issue in this pull request.
I also noticed and fixed a typo in `single_head_replacement_hook`.

Fixed hooks for single head SAEs

---

sae_lens/sae_training_runner.py

Replaces `/` with `__` when saving artifact to wandb.
Fixes #223 (issue)

Fix SAE failing to upload to wandb due to artifact name.

---

sae_lens/sae.py
sae_lens/training/training_sae.py

load_from_pretrained currently defaults dtype to float32 if a dtype is not specified. The issue is that we sometimes want to just load the SAE with the SAE's configured dtype, instead of setting one manually or defaulting to float32.
this does the following:
1) make load_from_pretrained default to dtype = None
2) if dtype is None, then use the SAE config's dtype
3) applies the same fix to both SAE and TrainingSAE
4) TrainingSAE's load_from_pretrained now also respects device override

fix: load_from_pretrained should not require a dtype nor default to float32

---

sae_lens/sae.py
sae_lens/training/training_sae.py

Somehow our hooks for SAE in were in the wrong place. Shouldn't affect training but annoying if you're hooking the input for analysis.
Fixes #232 

fix: sae hook input location

---

sae_lens/sae.py
tests/unit/training/test_sae_basic.py

Previously it was easy to call .to on the SAE and have the sae.cfg.dtype or sae.cfg.device not change. This is bad as it can lead to confusing results. 
Fixes #233 

fix sae to method

---

pyproject.toml
sae_lens/training/sae_trainer.py
tests/unit/training/test_evals.py
tutorials/Hooked_SAE_Transformer_Demo.ipynb

Corrected issue with eval configs not using the parameters from the trainer config. n_eval_batches and eval_batch_size_prompts will now be respected by the training eval config.

Trainer eval config will now respect trainer config params

---

pyproject.toml
sae_lens/analysis/hooked_sae_transformer.py
tests/unit/analysis/test_hooked_sae_transformer.py

Addresses https://github.com/jbloomAus/SAELens/issues/231. use_error_term is now a parameter for add_sae, run_with_saes, and run_with_cache_with_saes, and SAEs will be returned to their former states after the latter two functions execute (even if detached).

Use error term param

---

sae_lens/analysis/neuronpedia_integration.py

Minor change to Neuronpedia API for consistency. API Key is now in header, not body.

fix: Neuronpedia API key is now in header, not in body

---

pyproject.toml
sae_lens/training/optim.py
sae_lens/training/sae_trainer.py
tests/unit/training/test_optim.py

This PR updates pyproject.toml to pull in newer versions of the `automated-interpretability` dependency. This dependency was recently updated to relax numpy and scikit-learn dependencies to help make SAELens easier to install, especially on colab. However, since the version number for `automated-interpretability` is `0.0.x`, poetry's `^` dependency operator won't update to new versions automatically. This PR changes the dependency specification for `automated-interpretability` to `>=0.0.5,<1.0.0` to allow minor and patch versions of this library to be automatically installable.
Fixes #246 

fix: update automated-interpretability dep to use newly released version

---

docs/training_saes.md

Updating the slack link in the docs to use the same URL as in the README, as the docs slack link appears to have expired.
Fixes #253 

chore: updating slack link in docs

---

docs/index.md
docs/training_saes.md
sae_lens/__init__.py
sae_lens/sae.py
sae_lens/training/upload_saes_to_huggingface.py
tests/unit/training/test_sae_from_pretrained.py
tests/unit/training/test_upload_saes_to_huggingface.py
tutorials/uploading_saes_to_huggingface.ipynb

This PR adds a `upload_saes_to_huggingface()` function which uploads a dictionary of SAEs into a huggingface repo. This PR also adjusts the `SAE.from_pretrained()` function so that if the users passes a huggingface repository directly as the `release` param, the SAE can be directly loaded from huggingface even if it's not in the `pretrained_saes.yaml` file. 
An example repo generated from this function can be seen at https://huggingface.co/chanind/sae-lens-upload-demo. The README.md is also autogenerated as part of the upload.
This PR also adds a tutorial notebook, `uploading_saes_to_huggingface.ipynb` and adds a corresponding section to the training docs.  A screenshot from the new training docs is show below:
Fixes #234

feat: support uploading and loading arbitrary huggingface SAEs

---

sae_lens/tokenization_and_batching.py
tests/unit/training/test_tokenization_and_batching.py

This PR fixes an issue where memory usage spikes and crashes the Python interpreter when batching extremely long samples. I found that I was unable to run pretokenization on the [monology/pile-uncopyrighted dataset](https://huggingface.co/datasets/monology/pile-uncopyrighted), and discovered that the reason is this dataset includes some extremely long text samples, upwards of 47 million characters in a single sample.
Our batching code previously would remove a single batch of tokens from the sample, and then return the batch and the remaining tokens. However, by returning the remaining tokens, this causes a lot of copies of this huge tensor, and seems to cause memory and performance issues.
To address this, this PR instead keeps track of an int offset within the sample and simply …

fix: fix memory crash / perf improvement when batching huge samples

---

docs/generate_sae_table.py
docs/sae_table.md
sae_lens/analysis/neuronpedia_integration.py
sae_lens/pretrained_saes.yaml
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/toolkit/pretrained_saes_directory.py
tests/benchmark/test_eval_all_loadable_saes.py
tests/unit/toolkit/test_pretrained_saes_directory.py
tests/unit/training/test_sae_from_pretrained.py

This PR solves a few problems so that supporting Gemma Scope on Neuronpedia can be more streamlined. 
Specific changes include:
- Using paths in the pretrained_saes.yml that point to the specific SAE for any hookpoint (out of 5 or so different sparsity levels) which we will support on Neuronepedia. We found a few inconsistencies with the "canonical" folder in huggingface and this will make it simpler. 
- We store the neuronpedia id for an SAE in the pretrained_cfg.yaml so that it's always easy to work out which Neuronpedia SAE matches which SAE in SAE Lens. 
- I added Gemma Scope SAEs that were previously not yet in the yaml.

feat: updated pretrained yml gemmascope and neuronpedia ids

---

pyproject.toml

This PR adds more metadata to pyproject.toml which PyPI will automatically parse and show on the [SAELens PyPI page](https://pypi.org/project/sae-lens/). This will add links to the git repo, homepage, keywords, topic, and license. This is minor, but doesn't hurt to add and makes the project look a bit more polished when people land on the PyPI.

chore: adding more metatadata to pyproject.toml for PyPI

---

sae_lens/pretrained_saes.yaml

fix: gemma scope saes yml. 16k for Gemma 2 9b was missing entries. 

---

pyproject.toml
sae_lens/sae_training_runner.py
sae_lens/toy_model_runner.py

Attempting to fix docs failures, e.g. https://github.com/jbloomAus/SAELens/actions/runs/10547867695/job/29517908592. I'm struggling to reproduce this locally and don't see others reporting this same issue. A first attempt is to just update all the mkdocs dependencies and see if that resolves the issue.
This PR also adds `type: ignore` comments to `wandb.finish()` and `wandb.log_artifact()`, as it looks like 0.17.8 broke these types in wandb, and now our CI is failing as a result. More info here: https://github.com/wandb/wandb/issues/8248

chore: updating mkdocs deps

---

.gitignore
tutorials/training_a_sparse_autoencoder.ipynb

1. Removes an html output file (and adds them to .gitignore) to remove some of the repo size (25MB file of unnecessary outputs). 
2. Updates the basic training tutorial comment up top to link to the correct repo. 
Just a tutorial update.

Cleanup basic tutorial

---

sae_lens/training/sae_trainer.py
tests/unit/training/test_sae_trainer.py

Don't log the ghost grads if you're not using them.
There should be no performance impact to these changes.

saelens: only log ghost grad if you've enabled it

---

docs/citation.md
docs/index.md

This PR updates the `howpublished` url in citations to the Github repo, matching what's in the `README.md`. Previously, this was blank.

updating howpublished url in docs

---

docs/training_saes.md
sae_lens/config.py
sae_lens/load_model.py
sae_lens/pretrained_saes.yaml
sae_lens/sae.py
sae_lens/toolkit/pretrained_saes_directory.py
sae_lens/training/training_sae.py
tests/unit/analysis/test_hooked_sae.py
tests/unit/toolkit/test_pretrained_saes_directory.py
tests/unit/training/test_config.py

Modifications that TransformerLens makes to model weights can affect SAE performance and transferability with other code bases (though this effect is generally small, it can be pronounced for some SAEs). In particular, GPT2 Small res-jb and res-jb-feature-splitting SAEs (especially later layers) show worse performance if `center_writing_weights` is set to False when loading a `HookedTransformer`. It seems like other SAEs tend not to be affected by `center_writing_weights` which is somewhat interesting. 
To avoid further issues, we've made the following changes:
1. `model_from_pretrained_kwargs` is now part of the `SAEConfig` class. 
2. We've set an override for affected SAEs, and a warning to encourage users to load the model appropriately
```
SAELens/sae_lens/sae.py:136): UserWarning: …
```

fix: centre writing weights defaults

---

sae_lens/pretrained_saes.yaml

The Neuronpedia IDs do not contain `-it` in the SAE IDs.

fix: Gemma Scope 9b IT ids for Neuronpedia

---

sae_lens/pretrained_saes.yaml

The OAI mid SAEs (32k and 128k) were missing neuronpedia entries. This adds them.

fix: add OAI mid SAEs for neuronpedia

---

sae_lens/pretrained_saes.yaml

The OAI SAE ids on Neuronpedia were named incorrectly. This fixes them.

fix: neuronpedia oai v5 sae ids

---

sae_lens/sae.py

There are two issues with the current error message for SAE ID for not found:
1. The list of valid IDs can be absurdly long so doesn't even make the whole error fit:
2. If users try to use e.g. `gemma-scope-2b-pt-res` we should give a hint that they might want to use `gemma-scope-2b-pt-res-canonical` instead so they don't need to specify `average_l0`. Here's a screenshot of the new behavior:
~Fixes # (issue)~
I have not implemented a training change.

Improve error message for Gemma Scope non-canonical ID not found

---

sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/training/activations_store.py
sae_lens/training/upload_saes_to_huggingface.py

Fixes `ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'`. This package was [refactored in HF](https://github.com/huggingface/huggingface_hub/commit/4aa2053707b2fa3391be2c126d98b47ad0fbf5d9) and no longer exists. Its new name is [`errors`](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/errors.py).

Fix imports from huggingface_hub.utils.errors package

---

sae_lens/pretrained_saes.yaml

In `pretrained_saes.yaml`, there is a reference to a Gemma Scope layer 11, 16k l0=79 SAE. However, this SAE does not exist in https://huggingface.co/google/gemma-scope-2b-pt-res/tree/main/layer_11/width_16k. Likely this SAE is a duplicate of the l0=80 SAE and was probably removed for that reason.
This PR removes this non-existent SAE from the `pretrained_saes.yaml` file.

fix: removing missing Gemma Scope layer 11, 16k, l0=79 sae

---

sae_lens/config.py
tests/unit/helpers.py
tests/unit/test_evals.py
tests/unit/training/test_activations_store.py
tests/unit/training/test_config.py
tests/unit/training/test_sae_basic.py
tests/unit/training/test_sae_initialization.py
tests/unit/training/test_sae_trainer.py
tests/unit/training/test_sae_training.py

Changes `LanguageModelSAERunnerConfig` so if `d_sae` and `expansion_factor` are not `None`, `__post_init__()` raises a `ValueError` and if `d_sae` and `expansion_factor` are `None`, `__post_init__()` sets `expansion_factor` to `4`. `d_sae` and `expansion_factor` are both attributes to set the size of an SAE, and `expansion_factor` has a default value of `4`, for backward compatibility.
Fixes # https://github.com/jbloomAus/SAELens/issues/47

Add value error if both d sae and expansion factor set

---

tests/unit/test_evals.py
tests/unit/training/test_cache_activations_runner.py

Deletes `print()` in unit tests. In https://github.com/jbloomAus/SAELens/issues/43, we decided we should delete `print()` in unit tests.

deletes print() in unit tests

---

sae_lens/sae_training_runner.py

The training runner does not respect the W&B entity argument, even when it is specified in the configuration.
This change just uses the already defined entity argument from the configuration and feeds it to `wandb.init()`.

Add entity argument to wandb.init

---

sae_lens/training/activations_store.py
tests/unit/training/test_activations_store.py

Allowing for a `context_size` to be smaller than a dataset sample length in the case of a tokenized dataset. Adjusted tests to check for different cases of `context_size`. The motivation of this is to allow different applications like othelloGPT.

Fix context size of a tokenized dataset

---

sae_lens/toolkit/pretrained_sae_loaders.py

When loading the SAE bench TopK SAEs, such as the following:
```
sae, cfg_dict, sparsity = SAE.from_pretrained(
release = "sae_bench_pythia70m_sweep_topk_ctx128_0730",
sae_id = "blocks.4.hook_resid_post__trainer_10",
device = device
)
```
And using this [notebook](https://github.com/jbloomAus/SAELens/blob/main/tutorials/basic_loading_and_analysing.ipynb), I get an L0 of ~600, when it is supposed to be a TopK SAE, with [K=80.](https://huggingface.co/canrager/lm_sae/blob/main/pythia70m_sweep_topk_ctx128_0730/resid_post_layer_4/trainer_10/config.json) 
Printing the config, I see that: 'activation_fn_str': 'relu'
By …

Correctly load SAE Bench TopK SAEs

---

sae_lens/sae.py

This changes the `hook_sae_acts_post` so that it applies to the gated activations after you've multiplied by the masking values.
This problem comes about because "output of encoder" and "output of nonlinear activation function on feature magnitudes" aren't the same thing. Long term solution is to have 2 different hook points, but as a quick fix, I think this hook point should be here (and I would appreciate a quick fix if possible, since it'll make the [new ARENA material](https://colab.research.google.com/drive/1z3kK8MM5aCLX3LbIqqGZKTNvAI-fFCVY) work when it get to the visualization section!).

`hook_sae_acts_post` for Gated models should be post-masking

---

pyproject.toml

Our previous semantic release setup updates the `pyproject.toml:version` variable. However, this also has the unintended side-effect of replacing any `version = ` string in pyproject.toml with the new SAELens version. This broke black, since it now has an explicit `version = ` string set, as can be seen here: https://github.com/jbloomAus/SAELens/commit/e2a692a825dd8b138547c88188dfdf50b075cae5#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R44.
Fortunately, semantic-release has a [version_toml](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-toml) option which handles exactly this situation (their example even includes a Poetry pyproject.toml).

fix: properly manage pyproject.toml version

---

docs/generate_sae_table.py
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/toolkit/pretrained_saes_directory.py
tests/benchmark/test_eval_all_loadable_saes.py
tests/unit/toolkit/test_pretrained_sae_loaders.py
tests/unit/toolkit/test_pretrained_saes_directory.py

Adds a new function `get_sae_config()` which takes a `release` and `sae_id` and returns the config for an SAE. To get the config for an SAE, one shouldn't have to know the conversion function or download the weights, and one is more likely to know the `release` and `sae_id` than `repo_id` and `folder_name`. We also currently duplicate a lot of code across `pretrained_sae_loaders.py` and `generate_sae_table.py`.
Fixes #305, fixes #315 

Dedupe code to get config

---

sae_lens/pretrained_saes.yaml

We're adding more Gemma Scope SAEs to neuronpedia. Specifically, res-16k, mlp-16k, res-131k of L0 >=32 (the closest one).
We're calling these `gemmascope-mlp-16k-l0_32plus` (replace mlp-16k with res-16k, etc).
This is not quite a "fix" but also not a new feature or breaking change, but I do want it to deploy a new build.

fix: add neuronpedia links for gemmascope 32plus

---

.github/workflows/build.yml
tests/unit/conftest.py
tests/unit/training/test_cache_activations_runner.py

CI has started failing since merge #320 due to running out of space. It looks like this is due to loading and processing large datasets (c4-tokenized-2b). This PR replaces that dataset with a tiny tokenized version of c4-10k: https://huggingface.co/datasets/chanind/c4-10k-mini-tokenized-16-ctx-gelu-1l-tests. This is a tokenized version of the first 1k rows of the c4-10k dataset. It's split into 64 pieces, and the total dataset size is onlly 250kb (vs 2gb for c4-tokenized-2b)

chore: reduce test space usage in CI

---

sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_sae_loaders.py

SAE Bench Pythia models will now refer to the correct (deduped) version of Pythia-70m. In addition, I've updated the loader function so that the passed-in device arg actually works.

updated SAE Bench pythia model names (and loader device cfg)

---

sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/training/training_sae.py

Changes `read_sae_from_disk()` so that the `dtype` param is of type `Optional[torch.dtype]` and has a default value of `None`, in which case the function basically sets `dtype` to `cfg_dict["dtype"]`. `dtype` should be `cfg_dict["dtype"]`, unless the caller specifies a different value.
Fixes #230 

changes dtype default value in read_sae_from_disk()

---

sae_lens/pretrained_saes.yaml

Removes duplicate NP ids from non-canonical gemma-scope SAEs.

fix: fix duplicate np ids

---

tests/unit/test_evals.py

Adds unit tests for `all_loadable_saes()` and `get_saes_from_regex()`, and another test for `run_evals()`. There's no coverage for the first two functions, and there's no coverage for `single_head_replacement_hook()` and `single_head_zero_ablate_hook()` defined inside of the third function, at https://app.codecov.io/gh/jbloomAus/SAELens/blob/main/sae_lens%2Fevals.py.
Fixes #82

Add tests for evals

---

sae_lens/toolkit/pretrained_sae_loaders.py

This is a bug which was introduced last week. The issue seems to be that the `SAEConfigLoadOptions` class was introduced which contains the `device` field (default `None`), and this field wasn't set when device is not None. Before this change, the config was just loaded directly from HuggingFace without overriding its `device` value (which on HuggingFace presumably is "cuda").
Would be great if this PR could be merged soon if possible, and I can try to add tests for this kind of failure mode afterwards.

Supply `device` to `SAEConfigLoadOptions`

---

sae_lens/sae.py
sae_lens/training/training_sae.py
tests/unit/training/test_sae_basic.py

This PR adds test coverage to the JumpReLU and GatedSAE encode methods.
In doing this, I realized there's a lot of duplication  between all the encode variants and cleaned that up as well. I think there were some potential minor bugs in this duplication, for instance in `forward()`, when adding error term, we called `run_time_activation_norm_fn_out()`  after `reshape_fn_out()`, but we do the opposite in `decode()`.
It looks like most of the duplication between the `error` section of `forward()` and the normal `encode() / decode()` was there just to avoid triggering hooks, so I added a contextmanager `_disable_hooks()` which is used to disable hooks in this branch of the code while reusing our existing `encode() / decode()` methods. This should mean we don't need to worry about these …

fix: Test JumpReLU/Gated SAE and fix sae forward with error term

---

sae_lens/pretrained_saes.yaml

Fixes the incorrect layer 5 and uses the correct layer 12 for sparsity experiment instead.

fix: use the correct layer for new gemma scope SAE sparsities

---

sae_lens/sae.py
tests/unit/training/test_sae_basic.py

This PR implements the fix specified in #354 and updates tests.
Fixes #354

fix: normalize decoder bias in fold_norm_scaling_factor

---

sae_lens/config.py
sae_lens/sae.py
sae_lens/training/training_sae.py
tests/unit/test_jumprelu_sae.py
tests/unit/training/test_sae_basic.py
tests/unit/training/test_sae_initialization.py
tests/unit/training/test_sae_training.py

Adds logic to train JumpReLU SAEs. JumpReLU is a state-of-the-art architecture, so users should be able to train JumpReLU SAEs. Currently, they can load pre-trained JumpReLU SAEs and perform inference with them.
Fixes #330

Add logic to train JumpReLU SAEs

---

sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
tests/unit/toolkit/test_pretrained_sae_loaders.py

This PR unifies the code path for `from_pretrained` and `get_sae_config` so the config dict should match, and adds a test asserting this for a jbloom/gpt2 SAE.
Fixes #351

fix: load the same config from_pretrained and get_sae_config

---

sae_lens/training/sae_trainer.py
sae_lens/training/training_sae.py
tests/unit/training/test_gated_sae.py
tests/unit/training/test_sae_trainer.py
tests/unit/training/test_sae_training.py

This PR refactors the `TrainStepOutput` in `TrainingSAE.training_forward_pass()` to allow passing `losses` as a dict rather than a hardcoded set of specific losses. The current implementation requires always providing values for ghost grad loss and auxiliary loss, even when it doesn't make sense for the training method. As SAELens supports more architectures, there will likely be more losses like this that only make sense for certain architectures, so it makes sense to let the train forward step define the losses that make sense for the circumstances.
This should also make it easier for researchers to hack on the SAELens SAEs since it means they can define any losses they want to track.
This PR also allows the losses to remain as tensors rather than being floats. The current …

chore: more flexible training losses

---

docs/assets/saetable.css
docs/assets/saetable.js
docs/generate_sae_table.py
mkdocs.yml

I've noticed users sometimes get confused on the pretrained SAE table docs page about how to load a specific SAE in their code. This PR adds a "Load this SAE" link to each SAE in the pretrained SAEs table in docs. Clicking this link will pop up the code to load the specific SAE in SAELens, with a "Copy code" button to make it easy to copy into your own work.
The JS/CSS is a bit hacky but should do the job.

chore: adding 'Load this SAE' popup to docs table

---

docs/training_saes.md
pyproject.toml
sae_lens/sae_training_runner.py
tests/unit/conftest.py
tests/unit/training/test_sae_training_runner.py

This PR allows running SAE training via CLI. The interface is to run `python -m sae_lens.sae_training_runner` from CLI. All options in `LanguageModelSAERunnerConfig` are available as options to the CLI runner as well, so you can, e.g. run something like:
```bash
python -m sae_lens.sae_training_runner \
--model_name gemma-2-2b \
--dataset_path HuggingFaceFW/fineweb \
...
```
This makes it easier to run SAELens training on a HPC cluster where you typically submit a bash script to run for training.

feat: adding a CLI training runner

---

sae_lens/cache_activations_runner.py
tests/benchmark/test_cache_activations_runner.py
tests/unit/training/test_cache_activations_runner.py

Builds upon #321. Previously I used `dataset.save_to_disk` to write the final dataset, but this will rewrite the entire dataset to disk, which is very slow. Instead I manually move the shards to the standard hf format which allows us not to resave the entire dataset.
This should be externally identical, but just saving the dataset faster. My previous cached activation runner tests validate the change well.
Benchmarking cached activation benchmark on my mac:
```
poetry run py.test tests/benchmark/test_cache_activations_runner.py::test_cache_activations_runner -s
Old: Caching activations took: 81.5707
New: Caching activations took: 68.0761
```
I expect this to be even more pronounced for larger runs, where computing activations scales faster than disk speed.

Faster cleanup of sharded datasets

---

sae_lens/training/training_sae.py
tests/unit/training/test_training_sae.py

This PR adjusts standard SAE training to only scale sparsity penalty by decoder norm if `scale_sparsity_penalty_by_decoder_norm=True` in the config.
Fixes #363

fix: only scale sparsity by dec norm if specified in the config

---

sae_lens/evals.py
sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_sae_loaders.py

This pull request includes the following updates:
- add entries to Llama Scope SAEs in pretrained_saes.yaml
- implement Llama Scope loaders in pretrained_sae_loaders.py
- implement an option to not replacing bos activations when computing ce_loss_score in eval.py. This is necessary for SAEs trained with context starting with bos but is not trained with bos activations.

Add Llama Scope SAEs & improvements to evaluating ce scores.

---

sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_sae_loaders.py

Fixed minor bug affecting CI and also LlamaScope name casing.

fixed llamascope sae names and loader

---

tests/unit/training/test_config.py

Following #377, this PR adds tests which iterate over all the properties of `cfg.get_training_sae_cfg_dict()` and `cfg.get_base_sae_cfg_dict()` and ensure that there are no properties missing. This should help ensure that more bugs like #377 can't happen in the future.
-[x] chore: tests

chore: adding test that all config params pass to sae

---

pyproject.toml

This is a follow-up from #370, which added `typeguard` as a dependency to fix an import bug in transformer-lens (https://github.com/TransformerLensOrg/TransformerLens/issues/785). However, Bryce fixed that issue super-fast (https://github.com/TransformerLensOrg/TransformerLens/pull/787), so we no longer need to include `typeguard` explicitly in pyproject.toml. This PR removes this now unnecessary dependency..

fix: remove typeguard dependency

---

sae_lens/cache_activations_runner.py
sae_lens/config.py
sae_lens/training/activations_store.py
scripts/ansible/util/cache_acts.py
scripts/caching_replication_how_train_saes.py
tests/benchmark/test_cache_activations_runner.py
tests/unit/training/test_cache_activations_runner.py
tests/unit/training/test_config.py

Before `CacheActivationConfig` had a inconsistent config file for some interopability with `LanguageModelSAERunnerConfig`. It was kind of unclear which parameters were necessary vs redundant, and just was fairly unclear.
Simplified to the required arguments:
- `hf_dataset_path`: Tokenized or untokenized dataset
- `total_training_tokens`
- `model_name`
- `model_batch_size`
- `hook_name`
- `final_hook_layer`
- `d_in`
I think this scheme captures everything you need when attempting to cache activations and makes it a lot easier to reason about.
Optional:
```
activation_save_path # defaults to "activations/{dataset}/{model}/{hook_name}
shuffle=True
prepend_bos=True
streaming=True
seqpos_slice
buffer_size_gb=2 # Size of each buffer. Affects memory usage and saving freq
device="cuda" or "cpu" …
```

Cleaned up CacheActionsRunnerConfig

---

sae_lens/__init__.py
sae_lens/analysis/neuronpedia_integration.py
sae_lens/analysis/tsea.py
sae_lens/cache_activations_runner.py
sae_lens/config.py
sae_lens/load_model.py
sae_lens/sae_training_runner.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/toolkit/pretrained_saes.py
sae_lens/training/activations_store.py
sae_lens/training/training_sae.py
sae_lens/training/upload_saes_to_huggingface.py

Replaces `print()` with logging methods called on a logger, where we don't display console output for a command line script, and excluding notebooks and the `benchmark/tests` directory. This allows us to track the severity of events and makes it possible to configure the logging verbosity. Currently, we're just using `print()`.
Fixes #43

Replace print with logging

---

sae_lens/pretrained_saes.yaml

Fixes a typo in the pretrained yaml file.

fix: typo in pretrained yaml

---

sae_lens/pretokenize_runner.py
tests/unit/training/test_activations_store.py

It looks like `PreTrainedTokenizerBase` typing no longer has `bos_token_id` or other token IDs defined in the most recent version of transformers. I'm not sure if that was intentional by `transformers`, or an oversight, but this PR just ignore the typing for these token IDs so CI can pass.

chore: fix tokenizer typing for bos_token_id

---

sae_lens/analysis/hooked_sae_transformer.py
sae_lens/analysis/neuronpedia_integration.py
sae_lens/cache_activations_runner.py
sae_lens/config.py
sae_lens/evals.py
sae_lens/load_model.py
sae_lens/sae.py
sae_lens/tokenization_and_batching.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/toolkit/pretrained_saes.py
sae_lens/toolkit/pretrained_saes_directory.py
sae_lens/training/activations_store.py
sae_lens/training/optim.py
tests/unit/training/test_config.py

Replaces `assert` statements with code to raise exceptions when I'd expect that a user could see an `AssertionError` and excluding `assert` statements for `pyright` and in notebooks/the `tutorials` directory. I'd made a comment in https://github.com/jbloomAus/SAELens/pull/226#discussion_r1835621811 about `assert` statements in production code and we want to change them to code to throw exceptions when we'd expect users could see them fail.

Replace assert statements with exception code

---

sae_lens/pretrained_saes.yaml

Some of the GemmaScope SAEs on SAE Lens don't really exist, and vice versa. I basically made this fix manually. This script identifies them (at some point would be good to commit a check like this):
```
from huggingface_hub import HfApi
from sae_lens.toolkit.pretrained_saes_directory import get_pretrained_saes_directory
for repo_id in ["google/gemma-scope-2b-pt-res", "google/gemma-scope-9b-pt-res", "google/gemma-scope-27b-pt-res"]:
def get_repo_files(repo_id: str):
"""
Get all file names from a Hugging Face repository
Args:
repo_id (str): Repository ID (e.g., 'bert-base-uncased' or 'username/repo-name')
"""
api = HfApi()
files = api.list_repo_files(repo_id)
return files
huggingface_files = get_repo_files(repo_id)
sae_lens_files = …
```

Fixing GemmaScope SAEs listed in pretrained_saes.yaml

---

pyproject.toml

In https://github.com/jbloomAus/SAELens/pull/412/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R22, a dependency on typeguard < 3.0.0 was added. This means SAELens cannot be installed in any project uses any recent version of typeguard (typeguard is currently on v4.4.1, the most recent v2 release is from 2021). This includes all modern versions of Transformerlens, which SAELens depends on. SAELens does not use typeguard, so this restriction seems unnecessary.
This PR removes this dependency, so current SAELens versions can be installed without forcing very outdated dependencies in existing projects.

fix: remove restrictive typeguard dependency

---

sae_lens/cache_activations_runner.py
sae_lens/config.py
sae_lens/training/activations_store.py
sae_lens/training/sae_trainer.py
sae_lens/training/training_sae.py
tests/benchmark/test_cache_activations_runner.py
tests/unit/training/test_activations_store.py
tests/unit/training/test_cache_activations_runner.py

This PR adds an option `exclude_special_tokens` to the config, which can be set to `True` to ignore all special tokens in the tokenizer, or set to a list of ints corresponding to token IDs to explicitly ignore.
This works by keeping track of the token ids that correspond to each activation in the activation store, and filtering out the excluded tokens when generating training batches. This PR also updates the cache activations runner to add the token_ids that correspond to each activation to the generated dataset as well.
This PR doesn't make ignoring special tokens the default, but am happy to make that change if that makes more sense (or make the change with the next major version release).
Closes #333

feat: ignore special tokens in SAE training

---

sae_lens/evals.py

It looks like if there's multiple GPUs, where model and SAE are on different GPUs, then during evals the flattened mask can end up on the incorrect GPU and break the eval. This PR explicitly moves the mask to the same device as the tensor being masked.
I wish we could test this explicitly in CI, but as far as I know there's no way in torch to set a testing device 😢: https://github.com/pytorch/pytorch/issues/61654
Fixes #337

fix: ensure flattened_mask is on correct device in evals

---

sae_lens/config.py
sae_lens/sae_training_runner.py
tests/training/test_sae_training_runner.py

This PR allows passing dict options to the CLI runner encoded as JSON, based on https://github.com/lebrice/SimpleParsing/issues/335.
Fixes #422 

fix: properly parse CLI dict options as json

---

sae_lens/toolkit/pretrained_sae_loaders.py
tests/toolkit/test_pretrained_sae_loaders.py

Docs are currently failing to build since the deepseek r1 SAE config is missing. This PR fixes this by creating a proper config loader for the deepseek R1 SAE

chore: fixing docs sae table for deepseek SAE

---

sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_sae_loaders.py

**Failing tests seem to be caused by a connection error to pythia-14m config, which is irrelevant to this PR. As suggested by @hijohnnylin I ignore this.**
Supports llama scope r1 distill SAEs in https://huggingface.co/fnlp/Llama-Scope-R1-Distill/tree/main. This set includes 96 SAEs (32 layers * 3 data recipes). The 3 data recipes include
- 800M pretraining data ([Slimpajama](https://huggingface.co/datasets/Hzfinfdu/SlimPajama-3B))
- 400M pretraining data + 400M math reasoning data
- 800M math reasoning data ([OpenR1-Math-220k](https://huggingface.co/datasets/open-r1/OpenR1-Math-220k))
No dependency is required for this change.
Please links to …

Supports llama scope r1 distill SAEs

---

sae_lens/pretokenize_runner.py
tests/training/test_pretokenize_runner.py

Fixes bug with PretokenizerRunner when `streaming=True` due to differences in interface with `Dataset` and `IterableDataset`. Specifically, `num_proc` is an argument to the `map` method for the former but not the latter. Similarly, `Dataset` uses `set_format` and `IterableDataset` uses `with_format`. Added test.
Also replaced a usage of deprecated `pretokenize_runner ` with `PretokenizeRunner` in a separate test.
Fixes #441 

Fixed issue with PretokenizeRunner with streaming=True

---

sae_lens/config.py
sae_lens/pretokenize_runner.py
tests/training/test_pretokenize_runner.py

`PretokenizerRunner` doesn't support datasets `name` argument. Usually you can get around this by specifying the `data_dir`, but supporting this argument brings the interface more in line with the `datasets` interface. Additionally, the column name was previously not being tracked in the metadata, and now is. Finally, a pretokenizer test was using `pretokenize_runner` instead of `PretokenizerRunner`, which was deprecated, and has now been upgraded. 
Summary of updates:
- Added optional dataset name parameter
- Updated metadata to track dataset name and column name
- Added test for loading dataset with name argument and checking metadata
- Updated tests to use PretokenizeRunner instead of depricated pretokenizer_runner
Dependencies:
- Loads new (but small) dataset from HF for tests
Fixes # …

feat: Add support for dataset name in PretokenizeRunner

---

pyproject.toml
sae_lens/training/training_sae.py
tests/conftest.py
tests/training/test_training_sae.py

This PR fixes a minor issue with our topk aux loss implementation, where we calculate `k_aux` using `d_sae` instead of the correct `d_in`. This likely doesn't make a huge difference in practice, but can't hurt to fix. This PR also calls `detach()` on the residual error before calculating topk aux loss, similar to [dictionary_learning's implementation](https://github.com/saprmarks/dictionary_learning/blob/main/dictionary_learning/trainers/top_k.py#L297). This should help ensure that the aux loss only pulls dead latents towards the SAE error, and doesn't accidentally pull live latents towards dead latents.
This PR also adds a test asserting that our topk aux loss matches the sparsity implementation aside from a normalization factor.
As a side note, we should probably add an optional …

fix: base k_aux on d_in instead of d_sae in topk aux loss

---

sae_lens/sae_training_runner.py
sae_lens/training/activations_store.py
tests/training/test_sae_training_runner.py

Fixes #439 
When `b_dec_init_method` is set to `mean` or `geometric_median` we require getting activations from the buffer, however `set_norm_scaling_factor_if_needed` was not being called prior to this, meaning if `normalize_activations` was set to `expected_average_only_in` it would throw an error.
I added a call to `set_norm_scaling_factor_if_needed` directly before accessing the activations buffer inside `_init_sae_group_b_decs` to ensure the scaling factor is set before initialization. I also added a condition to `set_norm_scaling_factor_if_needed` to check whether the scaling factor is already set to prevent it from being set twice.
An alternative solution would be to take this opportunity to resolve the TODO for `_init_sae_group_b_decs` and move that method to another class, which …

fix: Ensure activation scaling factor set before initializing b_dec

---

pyproject.toml
sae_lens/analysis/hooked_sae_transformer.py
sae_lens/analysis/neuronpedia_integration.py
sae_lens/config.py
sae_lens/evals.py
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/toolkit/pretrained_saes_directory.py
sae_lens/training/geometric_median.py
sae_lens/training/sae_trainer.py
sae_lens/training/training_sae.py
sae_lens/tutorial/tsea.py
tests/analysis/test_hooked_sae_transformer.py
tests/helpers.py
tests/training/test_activations_store.py

Adds a lint rule to check for banned imports. We want to stop using `Union`, `Optional`, `Dict`, `List`, etc. since using shorthands is recommended and type aliases have been deprecated. @chanind had made a comment in https://github.com/jbloomAus/SAELens/pull/425#discussion_r1992034386 about this.

chore: adds Ruff rule to check for banned imports

---

sae_lens/pretrained_saes.yaml

This PR adds a bunch of Matryoshka SAEs for Gemma-2-2b, Gemma-2-9b, and Gemma-3-1b to the list of pretrained SAEs.

feat: adding matryoshka-dc saes

---

sae_lens/pretrained_saes.yaml

Removes the `layer_20/width_262k/canonical` SAE from `pretrained_saes.yaml`. We want to ensure the accuracy of the file, and this SAE was not found in (deleted from) Hugging Face.
Fixes #456

removes deleted gemma-scope-9b-pt-res-canonical SAE

---

.github/workflows/deploy_docs.yml

This PR adds the huggingface token secret to the docs CI step, so we can build docs hopefully without getting too many requests errors from huggingface

chore: adding HF_TOKEN to docs build in CI

---

sae_lens/pretrained_saes.yaml

Bizarrely, the layer 11 SAE for gemma-2-9b is missing. This PR temporarily removes it from the list of SAEs until I can get it retrained and uploaded.

fix: removing strangely missing gemma 2 9b SAE

---

README.md
docs/citation.md
docs/index.md

This PR fixes the bibtex citation format in the docs/readme. Bibtex requires `and` between names, not a comma.

chore: fixing incorrect citation format

---

sae_lens/training/activations_store.py
tests/training/test_activations_store.py

`ActivationsStore.estimate_norm_scaling_factor()` was taking the first sample from each batch, when it looks like it was meant to take the first (and only) layer. This fixes it to use the whole batch instead.

fix: Use the whole batch when estimating norm scaling factor.

---

sae_lens/evals.py

Deletes `dict_to_nested()`. It's unused and not documented.

deletes dict_to_nested()

---

sae_lens/training/training_sae.py
tests/training/test_sae_initialization.py

This PR fixes a bug with the `decoder_heuristic_init` option. The decoder should be initialized to random directions (see: https://transformer-circuits.pub/2024/april-update/index.html#training-saes). However, SAELens was using `torch.rand`, which picks values at random between 0 and 1, rather than `torch.randn` which positive or negative values according to a normal distribution. As a result, the decoder had only positive values when using `decoder_heuristic_init`, which basically forces all the decoder latents into a tiny portion of the full subspace of size `1/d_in` of the full `d_in` vector space.
This PR fixes this issue and adds a test so we can't accidentally revert back to this behavior.

fix: heuristic init should place latents anywhere in the space

---

sae_lens/toolkit/pretrained_sae_loaders.py

We have received bug reports that Llamascope SAEs are not loaded properly, with large L0's on all tests. We have not identified which commit led to this incompatibility. Now with jumprelu threshold scaled with norm_scaling_factor they should work fine.

Fix abnormally large llamascope L0.

---

.github/workflows/deploy_docs.yml
pyproject.toml

📚 Add Versioned Documentation with Mike. This change was proposed/implemented by Claude 4, and I don't think it's really possible to fully test it out without actually doing a push / deploy. The goal here is that we should be able to have the new alpha refactor docs live along with the existing full release docs, and as an added bonus, keep around old docs versions too.
This PR implements versioned documentation deployment using [mike](https://github.com/jimporter/mike), allowing us to maintain documentation for multiple versions of SAE Lens simultaneously.
- Added `mike = "^2.0.0"` to dev dependencies for versioned MkDocs deployment
- Enhanced `.github/workflows/deploy_docs.yml` to support:
- Release-triggered documentation deployment
- Branch-based documentation deployment
- Automatic …

chore: versioned docs

---

.github/workflows/deploy_docs.yml

Adds `-u` to move `latest` to the current version. We want to fix the build, and Deploy Docs is failing with
`error: alias 'latest' already exists for version 'v5.10.5'`.

fixes alias already exists error

---

sae_lens/config.py
sae_lens/load_model.py
sae_lens/toolkit/pretrained_sae_loaders.py
tests/toolkit/test_pretrained_sae_loaders.py

Adds functions to load SAEs trained with the `sparsify` library, from Hugging Face or disk. In #433, we made a change so that you can load an SAE trained using any library as long as you pass a correct arg to the `converter` param of `SAE.from_pretrained()`/`SAE.load_from_disk()`, and said we wanted to add this for SAEs trained with the `sparsify` library.

adds sparsify_huggingface_loader()

---

sae_lens/saes/sae.py
tests/saes/test_sae.py

This PR allows the old usage of `SAE.from_pretrained()` returning a tuple to still continue to work, to make the transition to SAELens v6 more graceful. This will output a deprecation warning if the user does this.

feat: allow old usage of SAE.from_pretrained() to continue to work

---

sae_lens/config.py
sae_lens/llm_sae_training_runner.py
sae_lens/pretokenize_runner.py
sae_lens/tokenization_and_batching.py
sae_lens/training/activations_store.py
tests/helpers.py
tests/training/test_activations_store.py
tests/training/test_tokenization_and_batching.py
tutorials/pretokenizing_datasets.ipynb

Adds a field, where if the value is `True`, excludes the BOS token between concatenated sequences, and a field, where if the value is `True`, disables concatenating sequences and ignores sequences shorter than the context size. Gemma 2 wasn't trained on BOS tokens and we want to match this during training. We can do this using `PretokenizeRunner`, but not without it.
Fixes #472

adds fields for sequence logic in ActivationsStore

---

sae_lens/training/sae_trainer.py
tests/_comparison/sae_lens_old/training/sae_trainer.py

Deletes `TrainSAEOutput`. It's unused and not documented.

deletes TrainSAEOutput

---

.github/workflows/build.yml

Upgrades `python-semantic-release` to v10. Ideally, we want to have the latest stable version, and in v10, a change was made to improve readability of the changelog. I wanted to upgrade from v8 to v10 in #507 but the [docs](https://python-semantic-release.readthedocs.io/en/latest/upgrading/index.html) said we should upgrade from v8 to v9 first.

upgrades python-semantic-release to latest

---

sae_lens/config.py
tests/helpers.py
tests/training/test_config.py
tutorials/mamba_train_example.py

Deprecates `LanguageModelSAERunnerConfig.hook_eval`. We want to remove unused code but give users time to change their code. The field is unused.

deprecates eval_hook

---

.github/workflows/build.yml

This reverts commit c361af6893907a16b8d77ebec73b026fed1eb76d.
Downgrades `python-semantic-release` to v9. We want `CHANGELOG.md` to get updated, and it didn't after we upgraded to v10.

Revert "upgrades python-semantic-release to latest (#510)"

---

.github/workflows/build.yml
pyproject.toml
sae_lens/analysis/hooked_sae_transformer.py
sae_lens/loading/pretrained_sae_loaders.py
sae_lens/pretrained_saes.yaml
tests/analysis/test_hooked_sae_transformer.py
tests/loading/test_pretrained_sae_loaders.py

This PR adds the qwen transcoders from https://huggingface.co/mwhanna to SAELens pretrained list. This PR also adds a new `blocks.N.mlp.hook_in` to `HookedSAETransformer` to mimic what's in `circuit-tracer`.

feat: adding mwhanna qwen transcoders to pretrained list

---

pyproject.toml
sae_lens/analysis/neuronpedia_integration.py
tests/analysis/test_neuronpedia_integration.py

The `automated-interpretability` dependency causes a bunch of issues since it has very strict dependency requirement that are not frequently updated, and this means that SAELens thus can't be used with a lot of model python packages (e.g. see https://github.com/hijohnnylin/automated-interpretability/pull/4). `automated-interpretability` is only needed for Neuronpedia, so there's no reason normal users of SAELens should need this dependency anyway. This PR just moves the dependency to be optional, and can be installed with `pip install sae-lens[neuronpedia]`.
Fixes #517

move automated-interpretability to an optional dependency in sae-lens

---

.github/workflows/build.yml
sae_lens/loading/pretrained_sae_loaders.py
sae_lens/pretrained_saes.yaml
tests/loading/test_pretrained_sae_loaders.py

My previous commit https://github.com/jbloomAus/SAELens/pull/534 broke deploy docs because the doc build assumes that each pretrained_sae_loader has a corresponding config_getter.
This makes the config_getter for it, which basically just calls the sae_loader and gets the first value in the tuple.
Since the mntss CLT loader requires loading weights (and config getting is presumed to be a "lightweight" operation"), I've also added a warning log.
Fingers crossed that this doesn't OOM or timeout the CI!

fix: add config loader for mntss clt by layer

---

sae_lens/config.py
sae_lens/llm_sae_training_runner.py
sae_lens/training/sae_trainer.py
sae_lens/util.py
tests/helpers.py
tests/test_llm_sae_training_runner.py
tests/test_util.py
tests/training/test_sae_trainer.py

This PR adds an `output_path` option to the LLM training runner, where the inference version of the trained SAE is saved, defaulting to `"output"`. Previously, the final model was saved to a checkpoint called `final_<total training tokens>`, even if `n_checkpoints=0` is set, which seems like an unintuitive place to look for the final trained SAE, and is a confusing behavior for `n_checkpoints`. This PR separates checkpointing from saving the final output. A final checkpoint can be enable by setting `include_final_checkpoint=True` in the LLM runner config. 
In addition, this PR allows the user to set the `checkpoint_path` and `output_path` to `None` to disable saving checkpoints or the final model to disk entirely. If `checkpoint_path=None`, but wandb logging is enabled, checkpoints will …

feat: add `output_path` option to LLM training runner

---

docs/training_saes.md
sae_lens/saes/jumprelu_sae.py
tests/helpers.py
tests/saes/test_jumprelu_sae.py

This PR implements Anthropic's JumpReLU setup, based on https://transformer-circuits.pub/2025/january-update/index.html#DL. This has some minor changes from the proposal in #427, specifically:
`jumprelu_ste_method` is instead called `jumprelu_loss_mode`, with options `step` for DeepMind or `tanh` for Anthropic. On further inspection, Anthropic is still technically using a rectangle straight through estimator, but they changed the sparsity loss equation from what Deepmind used. 
I also changed the pre-enc loss to only get applied if SAE latents are actually dead rather than applying any time the latent doesn't fire. It just seems strange to apply a distorting loss to all latents when they're otherwise firing normally IMO.
This PR does not include Anthropic's `b_enc` init method, since when …

feat: support Anthropic's JumpReLU training setup

---

docs/custom_saes.md
mkdocs.yml

This PR adds docs for how to create custom SAE classes to extend SAELens, made possible by SAELens v6. The docs look like below:

chore: adding docs for making custom SAE classes
