jbloomAus/SAELens

research/run.ipynb
research/week_27_jan/ghost_grads.ipynb
sae_analysis/visualizer/data_fns.py
sae_training/config.py
sae_training/sparse_autoencoder.py
sae_training/train_sae_on_language_model.py

Ghost Grads are so awesome 👻 🎓

Ghost grads dev

---

tutorials/logits_lens_with_features.ipynb

Added a link to the alignment forum post to the logit lens SAE colab

Added link to AF post

---

README.md

Was reading through the README and noticed this. Nice little PR to get started. 
Test plan:
1. Load README
2. See dashboard image no longer broken.

Fix broken dashboard image on README

---

pyproject.toml
sae_lens/analysis/dashboard_runner.py
sae_lens/analysis/neuronpedia_runner.py

This PR uses the `sae-vis` version on PyPI so that we can hopefully successfully publish to PyPI.
This has no typing errors, but I commented out a few places in the neuronpedia runner, and didn't manually try creating a dashboard so it's possible it's not working well in practice.

fix: hotfix updating saevis version to use pypi

---

sae_lens/training/sparse_autoencoder.py
sae_lens/training/utils.py
tutorials/logits_lens_with_features.ipynb

Addressing two issues with logits_lens_with_features.ipynb
1. Backwardscompatible unpickler was not used leading to failure to load
2. Missing nltk import and loading of averaged_perceptron_tagger
3. Missing key for df_enrichment_score 
4. Fixed a graph name

Addressing notebook issues 

---

sae_lens/analysis/neuronpedia_integration.py
tests/unit/analysis/test_neuronpedia_integration.py

- Gets feature data from neuronpedia, including top activations
- Includes simple test

FEAT: Add API for getting Neuronpedia feature

---

sae_lens/analysis/neuronpedia_integration.py

- Improved initialization as suggested by @danbraunai-apollo [here](https://github.com/jbloomAus/SAELens/pull/112/files/c7eb14839ae4d2871c1434b717f80126c58216cf#r1584781389)
- Fix a bug where an API key passed in argument wasn't working (only worked when using env var)

Improved activation init, fix using argument to pass in API key

---

sae_lens/training/evals.py

Adds KL divergence between the base model and the model with SAE to the set of eval metrics.
- [] I have made corresponding changes to the documentation (n/a)

Add kl eval

---

sae_lens/training/evals.py

fix: Revert "Add kl eval" - too much memory consumption. 

---

scripts/ansible/README.md
scripts/ansible/configs_example/dev.yml
scripts/ansible/configs_example/shared.yml
scripts/ansible/playbooks/dev.yml
scripts/ansible/run-dev.yml
scripts/ansible/util/aws_ec2.yml

This enables an Ansible script that just launches an AWS instance with mounted S3 and SAELens/python environment for development.
Documentation is in `scripts/ansible/README.md`.

Ansible: dev only mode

---

tutorials/using_an_sae_as_a_steering_vector.ipynb

I have added a tutorial for sae steering vector.
Note: I havent added it to the README as not all are listed there. I can add it there on a further commit if this is accepted without changes and should be added.

SAE steering vector tutorial

---

sae_lens/training/sae_trainer.py

This is a small fix for a bug where the progress bar was being updated by `self.cfg.train_batch_size_tokens` steps but only every 100 steps, meaning that tracked progress was 100x slower than actual.
Can be reproduced with
```
from sae_lens import LanguageModelSAERunnerConfig, SAETrainingRunner
cfg = LanguageModelSAERunnerConfig(
training_tokens=32*200,
train_batch_size_tokens=32,
log_to_wandb=False
)
SAETrainingRunner(cfg).run()
```
See [this](https://colab.research.google.com/drive/1XyEXLGT2_BfHtr8KUV9QoDCMAk_zOFhS?usp=sharing) colab
- Not necessary in this case 
- Not necessary in this case 
- Manually tested using code provided above. Functionality of trainer already tested by other unit tests
Not necessary

fix: progress bar updates

---

sae_lens/toolkit/pretrained_sae_loaders.py
tests/unit/training/test_sae_basic.py

Fixes #208. We had some dumb defaulting. 

fix: Gated SAE Note Loading

---

sae_lens/analysis/neuronpedia_integration.py
tests/unit/analysis/test_neuronpedia_integration.py

A number of improvements/fixes to the Neuronpedia explanation/autointerp code:
- update to reflect new API
- new flags for save to disk and test key
- fix bug when scoring is disabled

Neuronpedia Autointerp/Explanation Improvements

---

sae_lens/pretrained_saes.yaml
tests/benchmark/test_eval_all_loadable_saes.py

Adding a couple more SAEs for Gemma-2b. They aren't great performance wise (seems like 16k isn't enough features especially towards the end of the model. But sharing them anyway, as better than nothing. 

add more bootleg gemma saes

---

sae_lens/pretrained_saes.yaml

Addresses https://github.com/jbloomAus/SAELens/issues/204. SAEs are now available in the directory and appear to function well.

Added OpenAI TopK SAEs to pretrained yaml

---

sae_lens/pretrained_saes.yaml
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
tests/unit/analysis/test_hooked_sae_transformer.py

Added support for loading Gemma-2 2b SAEs.

Gemma2 2b saes

---

docs/generate_sae_table.py
docs/sae_table.md
sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_sae_loaders.py

Fixes Docs for Gemma Scope SAE
- [ x I have not rewritten tests relating to key interfaces which would affect backward compatibility

Feat: Gemma Scope SAEs + fix gemma-scope docs

---

README.md

Remove duplicate link in readme

---

sae_lens/pretrained_saes.yaml

Added canonical SAEs for attn (there are no new SAEs, only making it clear which SAEs are canonical) - these ones will be on Neuronpedia.

feat: make canonical saes for attn

---

sae_lens/pretrained_saes.yaml

Adding SAEs from https://arxiv.org/abs/2405.12241 to pretrained.yml (already on neuronpedia).

add end-2-end saes to yaml

---

sae_lens/pretrained_saes.yaml
tests/unit/toolkit/test_pretrained_saes_directory.py

Some of the new neuronpedia id's weren't unique (mainly due to the SAEs from the instruction tuned model. Have fixed. 

fix: modify duplicate neuronpedia ids in config.yml, add test.

---

tutorials/tutorial_2_0.ipynb

The code to call to the API of https://www.neuronpedia.org/api/explanation/export was outdated

Tutorial: Corrected outdated code to call API

---

tutorials/logits_lens_with_features.ipynb

Uses the new, correct version of this function.
Just a tutorial / documentation update.

saelens: update get neuronpedia quicklist function in logit lens tutorial

---

tutorials/tutorial_2_0.ipynb

The API for neuronpedia explanation exports has changed, in order to significantly reduce server strain. This updates the tutorial to match.

Tutorial: Update usage of Neuronpedia explanations export

---

sae_lens/evals.py
sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_sae_loaders.py
tests/unit/test_evals.py
tests/unit/training/test_evals.py

This PR makes some minor modifications to the standard SAE Evals + adds SAEs from this [huggingface repo](https://huggingface.co/canrager/lm_sae) for an upcoming SAE benchmarking paper comparing SAEs of different architectures and during training.

feat: Add SAE Bench SAEs

---

README.md

There was an extra `}` I missed. Also, ending all lines with commas is preferred (but not essential).
(Skipped rest of boilerplate)

Fix second issue with citation

---

sae_lens/evals.py
sae_lens/pretrained_saes.yaml
sae_lens/toolkit/pretrained_sae_loaders.py

I've added some SAEs that were a late addition to GemmaScope. More info here:
- https://huggingface.co/google/gemma-scope-2b-pt-res/commit/0127b340ca980c3ee81df0275cea35f350f83488
- https://huggingface.co/google/gemma-scope-9b-pt-res/commit/940eab835d89afae729af50e3fce69d4b4a34ce9
Please note that these SAEs were not trained on all tokens from the embedding and so standard evaluations may give funky results. I have adjusted for the sqrt(d_model) scaling factor so you can hook them into the model.
More info in an upcoming publication / blog post (from the authors). 
- [] I have added tests that prove my fix is effective or that my feature works

feat: Add experimental Gemma Scope embedding SAEs

---

sae_lens/pretrained_saes.yaml

New SAE Bench SAEs where the checkpoints are log spaced rather than linear spaced. More detail in upcoming work.

fix: log-spaced-checkpoints-instead

---

sae_lens/training/activations_store.py

Change all of the printed "Warnings" to properly logged warnings in the activations-store.py.

Change print to warnings.warn messages in activations-store

---

README.md

Add Curt to citation

---

sae_lens/pretrained_saes.yaml

- adds missing gemmascope NP IDs
- update np id formats with new `__` suffix

fix: yaml was missing some gemmascope np ids, update np id formats

---

sae_lens/pretrained_saes.yaml

Some NP ids were missing model ids.

fix: np ids should contain model id

---

sae_lens/pretrained_saes.yaml

fix: last NP id fix, hopefully

---

docs/citation.md
docs/index.md
docs/training_saes.md
sae_lens/config.py

This PR updates the docs with some more tips for SAE training, adds jumprelu SAEs to the docs, and fixes some minor errors in the docs (missing params, inconsistent citation, etc...)

chore: updating training docs with tips / jumprelu

---

sae_lens/pretrained_saes.yaml

adds neuronpedia IDs for llama scope

fix: add neuronpedia ids for llamascope

---

sae_lens/pretrained_saes.yaml

fix: update neuronpedia yaml entries

---

sae_lens/pretrained_saes.yaml

missing neuronpedia yaml entry

fix: add missing neuronpedia yaml entry

---

sae_lens/pretrained_saes.yaml

add missing neuronpedia yaml entries

fix: add missing neuronpedia yaml entries

---

sae_lens/pretrained_saes.yaml

width for llamascope 32x was incorrect

fix: width for llamascope 32x was incorrect

---

pyproject.toml
sae_lens/analysis/hooked_sae_transformer.py
sae_lens/config.py
sae_lens/pretrained_saes.yaml
sae_lens/sae.py
sae_lens/toolkit/pretrained_sae_loaders.py
sae_lens/training/activations_store.py
sae_lens/training/toy_models.py
sae_lens/training/train_toy_sae.py
tests/unit/analysis/test_hooked_sae.py
tests/unit/analysis/test_hooked_sae_transformer.py

Added a new SAE from qresearch for L19 of deepseek-ai/DeepSeek-R1-Distill-Llama-8B.

Added qresearch SAE for distilled R1 LLaMa

---

sae_lens/config.py

Update config.py to remove duplicate of `train_batch_size_tokens: int… = 4096` in line 162 and line 188

Update config.py 

---

sae_lens/pretrained_saes.yaml

New neuronpedia links for deepseek r1

fix: neuronpedia links for DS R1

---

sae_lens/pretrained_saes.yaml

Pretrained YAML updates for Deepseek R1

fix: Pretrained YAML for ds r1

---

README.md

The Slack link was expired. replacing with a working one.

docs: Slack link was expired

---

sae_lens/pretrained_saes.yaml

Adding strangely missing layer 11 9b matryoshka SAE

fix: adding missing 9b matryoshka SAE

---

README.md
docs/citation.md
docs/index.md

Adding Anthony to the maintainer list in README/website, and updating the description in the README.

chore: update maintainer citation

---

benchmark/test_language_model_sae_runner.py
sae_lens/config.py
sae_lens/sae_training_runner.py
sae_lens/training/sae_trainer.py
scripts/replication_how_train_saes.py
scripts/replication_how_train_saes_control.py
scripts/sweep-gpt2-blocks.py
scripts/sweep-gpt2.py
scripts/test-autocast-lm.py
scripts/training_a_sparse_autoencoder_othelloGPT.py
tests/helpers.py
tests/toolkit/test_pretrained_saes_directory.py
tests/training/test_sae_training_runner.py
tutorials/mamba_train_example.py

Extracts fields related to logging to Wandb to a class `LoggingConfig`. We're trying to have less fields in `LanguageModelSAERunnerConfig` since there are a lot of them right now, which makes the config hard to use. This is part of a larger refactor.

extracts logging fields to class

---

pyproject.toml

Replaces a clone of **sparsify** with the latest version of `eai-sparsify` in `pyproject.toml`. We want to replace cloned repos with PyPI packages, and `eai-sparsify` has been published to PyPI.

fix: replaces clone of sparsify with eai-sparsify-package

---

sae_lens/pretrained_saes.yaml

Adds more of David's matryoshka SAEs for neuronpedia inference.

fix: add more matryoshka SAEs to neuronpedia inference

---

.github/workflows/build.yml

Upgrades `python-semantic-release` to v9. We want to fix the build, and the release job failed with
```
ERROR: failed to build: failed to solve: process "/bin/sh -c echo \"deb http://deb.debian.org/debian bullseye-backports main\" >> /etc/apt/sources.list;     apt-get update;    apt-get install -y git/bullseye-backports" did not complete successfully: exit code: 100
``` 
.

upgrades python-semantic-release

---

.github/workflows/build.yml
sae_lens/loading/pretrained_sae_loaders.py
tests/conftest.py
tests/loading/test_pretrained_sae_loaders.py
tests/training/test_activations_store.py

CI keeps failing due to running out of disk space. This PR tries to reduce disk usage in CI

chore: reduce disk usage in CI

---

sae_lens/pretrained_saes.yaml

Simple non-code update to the pretrained yaml to include mntss CLTs so that we can more easily load them.

feat: add mntss clts to pretrained yaml

---

sae_lens/pretrained_saes.yaml
tests/loading/test_pretrained_sae_loaders.py

- Updates pretrained_yaml to load SAEs from Andy Arditi.
- Adds a test for loading it

feat: add misaligned persona SAEs

---

tests/helpers.py
tests/saes/test_sae.py

This PR adds a test for all architectures asserting the folding the scaling factor works as expected

chore: adding a test for folding scaling factor all architectures

---

.github/workflows/build.yml
tests/conftest.py
tests/training/test_activations_store.py
tests/training/test_load_model.py

We keep getting "out of space" errors on CI, so we need to figure out what tests are causing this and fix them

track disk usage in tests to figure out where disk is going
